SET DATABASE SQL SYNTAX ORA TRUE;

INSERT INTO PRODUCT_ITEM (product_id, product_sku) VALUES(PRODUCT_ITEM_SEQ.NEXTVAL, 'XOXO');
INSERT INTO PRODUCT_ITEM (product_id, product_sku) VALUES(PRODUCT_ITEM_SEQ.NEXTVAL, 'YOLO');
INSERT INTO PRODUCT_ITEM (product_id, product_sku) VALUES(PRODUCT_ITEM_SEQ.NEXTVAL, 'TOTO');
INSERT INTO PRODUCT_ITEM (product_id, product_sku) VALUES(PRODUCT_ITEM_SEQ.NEXTVAL, 'ABCD');
INSERT INTO PRODUCT_ITEM (product_id, product_sku) VALUES(PRODUCT_ITEM_SEQ.NEXTVAL, '1234');