SET DATABASE SQL SYNTAX ORA TRUE;

INSERT INTO PRODUCT_ITEM (product_id, product_sku, product_cost) VALUES(PRODUCT_ITEM_SEQ.NEXTVAL, 'XOXO', 1.99);
INSERT INTO PRODUCT_ITEM (product_id, product_sku, product_cost) VALUES(PRODUCT_ITEM_SEQ.NEXTVAL, 'YOLO', 2.99);
INSERT INTO PRODUCT_ITEM (product_id, product_sku, product_cost) VALUES(PRODUCT_ITEM_SEQ.NEXTVAL, 'TOTO', 5.00);
INSERT INTO PRODUCT_ITEM (product_id, product_sku, product_cost) VALUES(PRODUCT_ITEM_SEQ.NEXTVAL, 'ABCD', 15.50);
INSERT INTO PRODUCT_ITEM (product_id, product_sku, product_cost) VALUES(PRODUCT_ITEM_SEQ.NEXTVAL, '1234', 22.00);